//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payxat.Repository.DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int c_ID { get; set; }
        public string c_Name { get; set; }
        public string c_Phone { get; set; }
        public string c_Email { get; set; }
        public string c_Message { get; set; }
        public Nullable<System.DateTime> c_Date { get; set; }
    }
}
