//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payxat.Repository.DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int U_ID { get; set; }
        public string U_Name { get; set; }
        public string U_Password { get; set; }
        public int U_Type { get; set; }
    }
}
